module.exports = {
  NONEXISTENT_KEYRING_ACCOUNT:
    "The sender address does not exist in the keyring.",
  ADDRESS_NOT_PRESENT: "This address is not present in the vault",
  INCORRECT_ENCRYPTION_KEY_OR_VAULT: "Incorrect Encryption Key or vault string",
  ENTER_CREDS: "Please enter both encryptionKey and pin",
  WRONG_MNEMONIC: "Incorrect mnemonic passed",
  INCORRECT_PIN: "Incorrect pin",
  NO_ACCOUNTS_FOUND: "No accounts found for this chain",
  CHAIN_NOT_SUPPORTED: "The selected chain is not supported",
  UNSUPPORTED_NON_EVM_FUNCTIONALITY:
    "This functionality is not supported for non-EVM chains.",
  INCORRECT_PIN_TYPE: "Wrong pin type, format or length",
  ADDRESS_ALREADY_PRESENT: "This address is already present in the vault",
  SHOULD_BE_AN_ARRAY: "Addresses and chains should be an array",
  INVALID_NETWORK: "Invalid network selected",
  INCORRECT_CURRENT_PIN: "The current pin passed is incorrect",
  INCORRECT_LABEL_TYPE: "Label should be a valid string",
  REQUEST_LIMIT_EXCEEDED: "Request limit exceeded. Please retry later",
  REQUEST_BLOCKED: "Requests to method blocked",
  INVALID_API_KEY: "Invalid API key passed",
  VAULT_NOT_INITIALIZED: "Vault not initialized",
  INVALID_IDENTITY_REQUEST: "Invalid identity request object",
  INVALID_REDIRECT_URI: "Invalid redirect URI",
  INVALID_REDIRECT_URL: "Invalid redirect URL",
  IDENTITY_RETRIEVAL_FAILED: "Failed to retrieve identity",
  INVALID_IDENTITY: "Invalid identity object",
  INVALID_PROVIDER: "Invalid identity provider",
};
