name: automerge
on:
  workflow_dispatch:
#   push:
#     branches:
#       - feature-*
#       - bugfix-*
#   pull_request:
#     branches:
#         - feature-*
#         - bugfix-*
#     paths:
#       - package.json
#       - CHANGELOG 
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
#   status: {}

jobs:
  call-feature&bugfix:
    uses: ./.github/workflows/feature&bugfix.yml
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
          name: automerge
          uses: "pascalgn/automerge-action@v0.15.6"
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            MERGE_LABELS: "automerge"
