# # This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Feature/Bugfix branch

on:
#   workflow_call:
  push:
    branches:
      - feature-*
      - bugfix-*
  pull_request:
    branches:
        - feature-*
        - bugfix-*
        - devops-test
    paths:
      - package.json
      - CHANGELOG 
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
#   status: {}  
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Setting up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Installing dependencies 
      run: npm ci
      
    - name: Running tests
      run: npm run test
      
    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-summary-path: ./coverage/coverage-summary.json
        title: My Jest Coverage Comment
        summary-title: My Summary Title
        badge-title: Coverage
        hide-comment: false
        create-new-comment: false
        hide-summary: false
        junitxml-title: My JUnit Title
        junitxml-path: ./coverage/junit.xml
        coverage-title: My Coverage Title
        coverage-path: ./coverage.txt
      
  automerge:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: automerge PR
      if: success()
      uses: pascalgn/automerge-action@v0.15.6
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#       with:
#         repo-token: ${{ secrets.DEVOPS_TOKEN }}
#         merge-method: merge
#         delete-branch: false
#         MERGE_LABELS: ""
